# ==============================================================================
# Amplicon Barcode Analysis Pipeline Configuration
# ==============================================================================
# This file contains user-configurable options for the pipeline.
# Values here can later be overridden via CLI arguments if desired.
# ==============================================================================

# ------------------------------------------------------------------------------
# Input and output paths
# ------------------------------------------------------------------------------
paths:
  # Mandatory output directory for all pipeline results.
  output_folder: "/g/steinmetz/link/Amplicon_barcode_analysis/snake_test/tiny_test_set_pe_3x_v1"
  # output_folder: "/g/steinmetz/link/Amplicon_barcode_analysis/Jia_CM_prelim"
  # output_folder: "/scratch/link/Amplicon_barcode_analysis/HepG2_dual_rep_GALNAC_bcwithqc"
  
  # Mandatory input directory for fastq files
  input_folder: "/g/steinmetz/link/Amplicon_barcode_analysis/RAW/tiny_test_set_pe_3x"
  # input_folder: "/g/steinmetz/link/Amplicon_barcode_analysis/RAW/2026-07-07_Jia_CM_screen_initial"
  # input_folder: "/g/steinmetz/link/Amplicon_barcode_analysis/RAW/tiny_test_set_pe_input_only"
  # input_folder: "/g/steinmetz/link/Amplicon_barcode_analysis/HepG2_dual_rep_GALNAC/QC_filtered"

  # Mandatory library file, supported formats: .tsv, .csv, .xlsx, .rds (dataframe)
  # See 'library_formatting_requirements.txt' 
  # library_path: "/g/steinmetz/link/Amplicon_barcode_analysis/library/whole_genome_sublibs_1_to_4_merged_sgRNA_df.rds"
  library_path: "/g/steinmetz/link/Amplicon_barcode_analysis/library/CM_specific_library.rds"
  
  # Mandatory bcwithqc config.yaml path
  # bcwithqc_config_path: "/g/steinmetz/link/Amplicon_barcode_analysis/library/bcwithqc_config_whole_genome_sublibs_1_to_4.json"
  bcwithqc_config_path: "/g/steinmetz/link/Amplicon_barcode_analysis/library/bcwithqc_config_CM_specific_library.json"
  
  # Optional but recommended input_fastq_name_parser.xlsx
  # For matching file names to pipeline specific names.
  # fastq_name_table_xlsx: "/g/steinmetz/link/Amplicon_barcode_analysis/bcwithqc_test/input_fastq_name_table_template.xlsx"
  fastq_name_table_xlsx: "/g/steinmetz/link/Amplicon_barcode_analysis/library/tiny_test_set_pe_3x.xlsx"

# ------------------------------------------------------------------------------
# Read counting settings
# ------------------------------------------------------------------------------
counting:

  # Type of count data used downstream.
  # Allowed values:
  #   - "reads"
  #   - "umis"
  data_type: "umis"
  
  # When turned on this will treat each umi as a replicate in a different sublibrary. 
  umis_as_sublibs: true
 
# ------------------------------------------------------------------------------
# QC filtering with cutadapt
# ------------------------------------------------------------------------------
qc_filtering:
  # If true, FASTQ files are quality-filtered before read counting.
  # If false, the pipeline skips QC filtering.
  run: true

  # Minimum base quality passed to cutadapt.
  # Default: 20
  min_qual: 20

  # Minimum read length passed to cutadapt.
  # If null, the pipeline will determine this automatically by most common read length * 0.8.
  # bcwithqc will seperately filter out any reads that can no longer match the constant sequences. 
  # or infer from read length / STAR settings.
  min_length: null
      # can also be provided seperately for Forward and Reverse Reads
      # You need to remove the value from min length in that case (even null).
      # R1: 150
      # R2: 161
  
# ------------------------------------------------------------------------------
# Files, sublibraries, or samples to exclude
# ------------------------------------------------------------------------------
skip:
  # Individual files to skip.
  # Example: ["top20_library3_sample1", "unsorted_bin.fastq.gz"]
  files: []

  # Entire sublibraries to skip.
  # Example: ["L4", "sublib5"]
  sublibraries: []

  # Entire sample numbers to skip.
  # Example: ["1", "sampleA"]
  samples: []


# ------------------------------------------------------------------------------
# Controls and target lists
# ------------------------------------------------------------------------------
controls:
  # Extra targets or controls that should be included in the analysis.
  # any gene that matches an entry in include_controls will be treated as 
  # targeting, even if it is a control. 
  include_controls:
    - "EGFP"
    - "AAVS1_9"
    - "AAVS1_13"
    - "AAVS1_18"
    - "AAVS1_19"
    - "AAVS1_25"
    - "AAVS1_35"

  # Optional: restrict analysis to use only specified controls.
  use_only_these_controls: []

  # Are all non-targeting control sgRNAs the same across all sublibraries/replicates?
  same_controls_in_all_sublibraries: true

  # If true, keep 10% of control sgRNAs.
  # To check the distribution of control sgRNAs after MAUDE runs. 
  # This introduces randomness and should usually be false for final analyses.
  subsample_controls: false


# ------------------------------------------------------------------------------
# Replicate and grouping behavior
# ------------------------------------------------------------------------------
replicates:
  # Defines what should be treated as replicates in the experiment.
  # Allowed values:
  #   - ""             : no replicate grouping
  #   - "rep"          : each group of bins is its own replicate
  #   - "rep_sample"   : group by sample 
  #   - "rep_sublib"   : group by sublibrary
  method: ""

  # Automatically combine replicates where appropriate.
  auto_combine_replicates: false

  # How to combine data for guide-level statistics.
  # Allowed values:
  #   - "" <- none (don't type "none" just "")
  #   - "sample"
  #   - "sublib"
  combine_for_guide_stats: "sample"

  # How to combine data for gene-level statistics.
  # Allowed values:
  #   - "none"
  #   - "all"
  #   - "sample"
  #   - "sublib"
  combine_for_gene_stats: "none"


# ------------------------------------------------------------------------------
# Normalization and bin settings
# ------------------------------------------------------------------------------
normalization:
  # Normalization method.
  # Allowed values:
  #   - ""
  #   - "control_median"
  norm_method: "control_median"

  # Estimate missing input/unsorted data based on existing input/unsorted data.
  recover_input: true

# ------------------------------------------------------------------------------
# Filtering behavior
# ------------------------------------------------------------------------------
filtering:
  # Remove guides/rows with no reads or UMIs across all relevant bins.
  drop_0s: false

  # Remove guides that have a count of 0 in any bin.
  strict_mode: false

  # Minimum number of guides required per gene and replicate.
  # Use 0 to disable this filter.
  min_guides_per_gene: 0
# ------------------------------------------------------------------------------
# MAUDE consensus calling
# ------------------------------------------------------------------------------
# Due to subsampeling MAUDE has a small amount of internal randomness. 
# This can be handled by consensus calling -> running MAUDE multiple times. 
consensus:
  run: false
  n_reps: 19 # repetitions IN ADDITION to the inital MAUDE run

  high_confidence:
    FDR_threshold: 0.05
    hits_in_X_reps: 16
    correlation_heatmap: false # not currently implemented
    venn_diagram: false # not currently implemented

  explorative:
    FDR_threshold: 0.05
    hits_in_X_reps: 10
    correlation_heatmap: false # not currently implemented
    venn_diagram: false # not currently implemented
# ------------------------------------------------------------------------------
# Output naming
# ------------------------------------------------------------------------------
output:
  # Optional suffix added to output files/folders.
  # Useful for distinguishing different parameter runs.
  extra_suffix: ""
# ------------------------------------------------------------------------------
# Plotting options
# ------------------------------------------------------------------------------  
plots:

  read_count_violin:
    
    violin_y_limit: null # limit for the Y axis: Number of reads per sgRNA
    
  waterfall:
  
    mark_cntrl: true
    mark_special: null       # or ["AHSA1", "AGO2"]
    mark_N_top_hits: 3
    box_padding: 0.8
    no_text: false
    signif_lines: true
    mark_all_signif_level: 0.05 # FDR that is marked as significant e.g. 0.05
    break_in_plot: []        # e.g. [22, 70]
    top_padding: 0
    custom_title: null

    width: 8
    height: 6
    file_format: "png"
